name: Master
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Conventional Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
