name: Publish

on:
    push:
        branches: ["master", "main"]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: valitydev/action-frontend/setup-install@v2
            - name: Build
              run: npm run build
            - uses: valitydev/action-frontend/publish@v2
              with:
                  npm-token: ${{ secrets.NPM_TOKEN }}
